from __future__ import annotations

from carm.data.labeling import derive_oracle_action
from carm.data.schema import (
    Action,
    ConflictExample,
    ConflictType,
    CorruptedModality,
    EvidenceModality,
    Split,
)


def make_examples() -> list[ConflictExample]:
    examples = [
        ConflictExample(
            example_id="e1_clean",
            image_path="images/s1.jpg",
            text_input="A red car is parked.",
            question="What color is the car?",
            gold_answer="red",
            split=Split.TRAIN,
            conflict_type=ConflictType.NONE,
            corrupted_modality=CorruptedModality.NONE,
            corruption_family="clean",
            severity=0,
            evidence_modality=EvidenceModality.VISION_REQUIRED,
            oracle_action=Action.TRUST_VISION,
            source_image_id="s1",
            template_id="t_color",
            metadata={"topic": "vehicles"},
        ),
        ConflictExample(
            example_id="e1_text",
            image_path="images/s1.jpg",
            text_input="A blue car is parked.",
            question="What color is the car?",
            gold_answer="red",
            split=Split.TRAIN,
            conflict_type=ConflictType.ATTRIBUTE,
            corrupted_modality=CorruptedModality.TEXT,
            corruption_family="text_edit_attribute",
            severity=1,
            evidence_modality=EvidenceModality.VISION_REQUIRED,
            oracle_action=derive_oracle_action(EvidenceModality.VISION_REQUIRED, CorruptedModality.TEXT),
            source_image_id="s1",
            template_id="t_color",
            metadata={"topic": "vehicles"},
        ),
        ConflictExample(
            example_id="e1_vision",
            image_path="images/s1.jpg|blur|s2",
            text_input="A red car is parked.",
            question="What color is the car?",
            gold_answer="red",
            split=Split.TRAIN,
            conflict_type=ConflictType.OBJECT,
            corrupted_modality=CorruptedModality.VISION,
            corruption_family="vision_blur",
            severity=2,
            evidence_modality=EvidenceModality.VISION_REQUIRED,
            oracle_action=derive_oracle_action(EvidenceModality.VISION_REQUIRED, CorruptedModality.VISION),
            source_image_id="s1",
            template_id="t_color",
            metadata={"topic": "vehicles"},
        ),
        ConflictExample(
            example_id="e2_clean",
            image_path="images/s2.jpg",
            text_input="Two dogs sit on grass.",
            question="How many dogs are there?",
            gold_answer="2",
            split=Split.VAL,
            conflict_type=ConflictType.NONE,
            corrupted_modality=CorruptedModality.NONE,
            corruption_family="clean",
            severity=0,
            evidence_modality=EvidenceModality.BOTH,
            oracle_action=Action.REQUIRE_AGREEMENT,
            source_image_id="s2",
            template_id="t_count",
            metadata={"topic": "animals"},
        ),
        ConflictExample(
            example_id="e3_clean",
            image_path="images/s3.jpg",
            text_input="The cup is right of the plate.",
            question="Where is the cup?",
            gold_answer="right",
            split=Split.TEST,
            conflict_type=ConflictType.NONE,
            corrupted_modality=CorruptedModality.NONE,
            corruption_family="clean",
            severity=0,
            evidence_modality=EvidenceModality.TEXT_REQUIRED,
            oracle_action=Action.TRUST_TEXT,
            source_image_id="s3",
            template_id="t_rel",
            metadata={"topic": "kitchen"},
        ),
    ]
    return examples
